#!/bin/sh

export DOT_PATH=$HOME/.dotfiles
export SHELL_NAME=$(ps -hp $$ | tail -n 1 | awk '{print $4}' | cut -c 2-)

_load_settings() {
  _dir="$1"
  if [ -d "$_dir" ];
  then
    for config in $_dir/*; do
      if [ -f "$config" ]; then
        . "$config"
      fi
    done
  elif [ -f "$_dir" ];
  then
    . "$_dir"
  else
    echo "Could not load setting $_dir"
  fi
}

local_modules="bundler docker general git npm vim yarn"

if [ "$(uname)" = "Darwin" ]; then
  local_modules="$local_modules brew osx"
fi

for local_module in $local_modules
do
  _load_settings "$DOT_PATH/configs/sh/modules/$local_module"
done

if [ -f ~/.shrc.local ]; then
  . ~/.shrc.local
fi

