#!/bin/sh

#
# Install Homebrew package manager along with packages I commonly use
#

fancy_echo() {
  fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

if which brew > /dev/null; then
  fancy_echo "Brew already installed"
else
  fancy_echo "Installing Homebrew ..."
      curl -fsS \
        'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
fi

fancy_echo "Updating brew..."
brew update
brew upgrade

fancy_echo "Installing Homebrew bundler..."
brew tap Homebrew/bundle

brew bundle --file=$XDG_CONFIG_HOME/brewfile/Brewfile

brew cleanup
brew cask cleanup
