---
- name: Install global NPM packages
  npm:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    global: yes
    executable: "{{ item.executable | default(omit) }}"
  with_items: "{{ npm_packages }}"

- name: Install global Pip packages
  pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ item.executable | default(omit) }}"
  with_items: "{{ pip_packages }}"

- name: Install global Ruby gems
  gem:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    user_install: no
    executable: "{{ item.executable | default(omit) }}"
  with_items: "{{ gem_packages }}"

- name: Install global Go packages
  shell: "{{ GOROOT }}/bin/go get -u {{ item.url }}"
  environment:
    GOPATH: "{{ GOPATH }}"
    GOROOT: "{{ GOROOT }}"
  with_items: "{{ go_packages }}"
  changed_when: false

- name: Install vim/Vundle packages
  shell: vim -c VundleInstall -c quitall
