#!/bin/bash

# adds CSI \e to start ANSI escape sequence
# surround colors codes with \[ \]
function escape_color {
  echo "\[\e$1\]"
}

function get_color_256 {
  echo $(escape_color "[38;5;$1m")
}

BLUE=$(get_color_256 "111")
PURPLE=$(get_color_256 "104")
YELLOW=$(get_color_256 "220")
ORANGE=$(get_color_256 "166")
GREEN=$(get_color_256 "106")
RED=$(get_color_256 "124")
COLOR_NONE="\e[0m"

function get_prompt {
  local env

  # don't show host unless we're ssh'ed to something else
  if [ -n "$SSH_CLIENT" ]; then
    env="@\h"
  fi

  # just shows user and path
  echo "${GREEN}[\T]${RED}${env}:${YELLOW}\W ${PURPLE}\$git_branch ${BLUE}\$ "
}

function print_colors {
  for C in {16..255}; do
    local color=$(get_color_256 "$C")
    echo -en "${COLOR_NONE}${color} - $C\n"
  done
}
