#!/bin/bash

# adds CSI \e to start ANSI escape sequence
# surround colors codes with \[ \]
function escape_color {
  echo "\[\e$1\]"
}

function get_color_256 {
  echo $(escape_color "[38;5;$1m")
}

BLUE=$(get_color_256 "117")
PURPLE=$(get_color_256 "141")
YELLOW=$(get_color_256 "228")
ORANGE=$(get_color_256 "220")
GREEN=$(get_color_256 "119")
RED=$(get_color_256 "202")
COLOR_NONE="\e[0m"

function get_prompt {
  local env

  # don't show host unless we're ssh'ed to something else
  if [ -n "$SSH_CLIENT" ]; then
    env="@\h"
  fi

  # just shows user and path
  echo "${GREEN}[\T]${RED}${env}:${ORANGE}\W ${PURPLE}\$git_branch ${BLUE}\$ "
}
