#!/bin/bash
echo 'Running rcm post-up hook'

if [ -f ~/.duti ]; then
  duti ~/.duti
fi

if [ ! -z "${GOPATH}" ]; then
  mkdir -p $HOME/Code/mdzhang/go/src/github.com/mdzhang
fi

# NB: causes cli to freeze up
~/.vim/bin/install
