#!/bin/bash
echo 'Running rcm post-up hook'

# vim +PluginInstall +qall

if [ -f ~/.duti ]; then
  duti ~/.duti
fi

if [ ! -z "${GOPATH}" ]; then
  mkdir -p $HOME/Code/mdzhang/go/src/github.com/mdzhang
fi
