#!/bin/bash
echo 'Running rcm pre-up hook'

# symlink XDG dirs
ln -s ~/.dotfiles/config ~/.config
ln -s ~/.dotfiles/cache ~/.cache

# for source code dir generally and golang dir
mkdir -p ~/src/mdzhang/go/src/github.com/mdzhang

# create GPG directories; silence output
gpg --list-keys > /dev/null

# grab Vundle/prezto/bashit/mutt source code
git submodule init
git submodule update --init --recursive