#!/bin/bash
read -p "Run pre-up hook? [y/n] " run_pre_up < /dev/tty

if [ "$run_pre_up" = "y" ]; then
  read -p "Step through tasks? [y/n] " step < /dev/tty

  if [ "$step" = "y" ]; then
    flag="--step"
  fi

  ansible-playbook pre.yml -i inventory --ask-sudo-pass $flag -vvvv < /dev/tty
else
  echo "Not running pre-up hook"
fi
