#!/bin/bash
echo 'Running rcm pre-up hook'

if ! [[ -L ~/.vim ]]; then
    rm -f ~/.vim
    ln -s $DOT_PATH/configs/vim ~/.vim
fi

if ! [[ -L ~/.nvimrc ]]; then
    ln -fs $DOT_PATH/nvimrc ~/.config/nvim/init.vim
fi

# create Plex directories
mkdir -p ~/media/data/movies
mkdir -p ~/media/data/tv
mkdir -p ~/media/data/books

mkdir -p ~/media/configs/plex
mkdir -p ~/media/configs/sickrage
mkdir -p ~/media/configs/couchpotato
mkdir -p ~/media/configs/transmission

# for source code dir generally and golang dir
mkdir -p ~/opt/mdzhang/go/src/github.com/mdzhang

# for neovim
mkdir -p ~/.config/nvim

# create GPG directories
gpg --list-keys

# grab Vundle/prezto/bashit source code
git submodule init
git submodule update --init --recursive
