#!/bin/sh

export DOT_PATH=$HOME/.dotfiles
export SHELL_NAME=$(basename $SHELL)
export XDG_CACHE_HOME=$HOME/.cache
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share

_load_settings() {
  _dir="$1"
  if [ -d "$_dir" ];
  then
    for config in $_dir/*; do
      if [ -f "$config" ]; then
        . "$config"
      fi
    done
  elif [ -f "$_dir" ];
  then
    . "$_dir"
  else
    echo "Could not load setting $_dir"
  fi
}

local_modules="xdg bundler cargo docker general git irssi kubectl newsboat npm pyenv vim yarn"

if [ "$(uname)" = "Darwin" ]; then
  local_modules="$local_modules brew osx"
fi

for local_module in $local_modules
do
  _load_settings "$XDG_CONFIG_HOME/sh/usr/$local_module"
done

if [ -f ~/.shrc.local ]; then
  . ~/.shrc.local
fi

