[tool.yamlfix]
quote_representation = "'"
whitelines = '1'
section_whitelines = '1'
preserve_quotes = true
sequence_style = 'block_style'
comments_min_spaces_from_content = 1
none_representation = ""
line_length = 500
