#!/bin/sh

rm -rf ~/Library/Application\ Support/Sublime\ Text\ 3/Packages

mkdir -p ~/Library/Application\ Support/Sublime\ Text\ 3/Packages

ln -s $DOT_PATH/configs/subl/User/ ~/Library/Application\ Support/Sublime\ Text\ 3/Packages
