#!/bin/sh

mkdir -p ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User

rm -f ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Preferences.sublime-settings
ln -s $DOT_PATH/configs/subl/User/Preferences.sublime-settings \
	  ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Preferences.sublime-settings

rm -f ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Package\ Control.sublime-settings
ln -s $DOT_PATH/configs/subl/User/Package\ Control.sublime-settings \
	  ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Package\ Control.sublime-settings
