default: config caveat

config:
	mkdir -p ~/Code && \
	mkdir -p ~/Pictures/Screenshots && \
	./osx.sh

caveat:
	echo "Some of these changes require a logout/restart to take effect"

.PHONY: default config caveat