---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-byte-order-marker
      - id: flake8
        language: system
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: detect-aws-credentials
      - id: no-commit-to-branch
        args: [--branch, develop, --branch, master]
  - repo: https://github.com/fzylogic/rubocop-pre-commit-hook
    rev: 5e0a725f6e50e60b7a292e23414e1a3b10316f0a
    hooks:
      - id: check-rubocop
  - repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
      - id: black
        language: system
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.8.1
    hooks:
      - id: terraform_fmt
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.0.1
    hooks:
      - id: ansible-lint
        files: \.(yml)$
        language: system
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.10.3
    hooks:
      - id: shellcheck
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v5.12.0
    hooks:
      - id: eslint
        name: eslint
        entry: ./node_modules/.bin/eslint
        args: [--ext=.js, --ext=.jsx]
        language: system
        files: \.(js|jsx)$
