repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language: system
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
        language: system
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.7.3
    hooks:
      - id: terraform_fmt
  - repo: https://github.com/ansible/ansible-lint.git
    sha: v3.3.1
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        language: system
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    sha: 1.10.2
    hooks:
      - id: shellcheck
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v5.10.0
    hooks:
      - id: eslint
        name: eslint
        entry: ./node_modules/.bin/eslint
        args: [--ext=.js, --ext=.jsx]
        language: system
        files: \.(js|jsx)$
